//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "interface"
 * f1 -> Identifier()
 * f2 -> InterfaceBody()
 */
public class InterfaceDeclaration implements Node {
   public NodeToken f0;
   public Identifier f1;
   public InterfaceBody f2;

   public InterfaceDeclaration(NodeToken n0, Identifier n1, InterfaceBody n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public InterfaceDeclaration(Identifier n0, InterfaceBody n1) {
      f0 = new NodeToken("interface");
      f1 = n0;
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

