//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( Query() )*
    * f1 -> ( InterfaceDeclaration() )*
    * f2 -> <EOF>
    */
   public void visit(Goal n);

   /**
    * f0 -> Identifier()
    * f1 -> "<="
    * f2 -> Identifier()
    * f3 -> "?"
    */
   public void visit(Query n);

   /**
    * f0 -> "interface"
    * f1 -> Identifier()
    * f2 -> InterfaceBody()
    */
   public void visit(InterfaceDeclaration n);

   /**
    * f0 -> "{"
    * f1 -> ( InterfaceMember() )*
    * f2 -> "}"
    */
   public void visit(InterfaceBody n);

   /**
    * f0 -> ResultType()
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> Type()
    * f4 -> Identifier()
    * f5 -> ")"
    * f6 -> ";"
    */
   public void visit(InterfaceMember n);

   /**
    * f0 -> BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public void visit(Type n);

   /**
    * f0 -> "boolean"
    */
   public void visit(BooleanType n);

   /**
    * f0 -> "int"
    */
   public void visit(IntegerType n);

   /**
    * f0 -> VoidType()
    *       | Type()
    */
   public void visit(ResultType n);

   /**
    * f0 -> "void"
    */
   public void visit(VoidType n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n);

}

